"""Centralized NERM API spec constraints used by tools."""

MAX_AUDIT_FILTERS = 5

AUDIT_ALLOWED_FILTER_KEYS = (
    "subject_type",
    "type",
    "subject_id",
    "workflow_name",
    "workflow_uid",
    "workflow_profile_type",
    "profile_type",
)

# API-spec/SDK-backed known audit subject types and event types.
# These are used for guidance and validation hints; the API may evolve over time.
AUDIT_SUBJECT_TYPES = (
    "Profile",
    "WorkflowSession",
    "Email",
    "FormAttributeForm",
    "FormAttribute",
    "Form",
    "IdentityProofingResult",
    "IdproxyPermission",
    "NeAttributeOption",
    "NeAttribute",
    "Notification",
    "WorkflowPage",
    "ProfilePage",
    "Permission",
    "PortalRegistrationWorkflow",
    "Portal",
    "ProfileTypeRole",
    "ProfileType",
    "RoleProfile",
    "NeprofileRole",
    "NeaccessRole",
    "IdproxyRole",
    "SecurityQuestion",
    "UserManager",
    "UserProfile",
    "UserRole",
    "User",
    "Validation",
    "VerificationEmail",
    "WorkflowAction",
    "CreateWorkflow",
    "UpdateWorkflow",
    "AutomatedWorkflow",
    "BatchWorkflow",
    "ExpirationWorkflow",
    "InvitationWorkflow",
    "LoginWorkflow",
    "PasswordResetWorkflow",
    "RegistrationWorkflow",
    "Get",
    "Post",
    "Patch",
    "Delete",
    "ApprovalAction",
    "AutomatedUser",
    "DelegateUser",
    "NeaccessUser",
    "NeprofileUser",
    "Page",
    "Role",
    "SamlConfiguration",
    "SchemaMapping",
    "SchemaMappingField",
    "Workflow",
)

AUDIT_EVENT_TYPES = (
    "AuditableProfileCreate",
    "AuditableProfileUpdate",
    "AuditableProfileDestroy",
    "AuditableBulkProfileUpdate",
    "AuditableProfileContributorAdd",
    "AuditableProfileContributorRemove",
    "AuditableProfileContributorRoleAdd",
    "AuditableProfileContributorRoleRemove",
    "AuditableProfileOwnerUpdate",
    "AuditableProfileWorkflowEvent",
    "AuditableWorkflowActionSkippedEvent",
    "AuditableWorkflowApprovedEvent",
    "AuditableWorkflowAssignedEvent",
    "AuditableWorkflowAutoAssignedEvent",
    "AuditableWorkflowBatchCompleteEvent",
    "AuditableWorkflowClosedEvent",
    "AuditableWorkflowDuplicateCheckStartEvent",
    "AuditableWorkflowDuplicateResolutionEvent",
    "AuditableWorkflowFailedEvent",
    "AuditableWorkflowIdentityProofedEvent",
    "AuditableWorkflowInvitationSentEvent",
    "AuditableWorkflowLdapProvidedEvent",
    "AuditableWorkflowNotificationSentEvent",
    "AuditableWorkflowPendingApprovalEvent",
    "AuditableWorkflowPendingAssignmentEvent",
    "AuditableWorkflowPendingFulfillmentEvent",
    "AuditableWorkflowFulfilledEvent",
    "AuditableWorkflowPendingIdentityProofEvent",
    "AuditableWorkflowPendingLdapEvent",
    "AuditableWorkflowPendingRequestEvent",
    "AuditableWorkflowPendingReviewEvent",
    "AuditableWorkflowProfileCreatedEvent",
    "AuditableWorkflowProfileSelectEvent",
    "AuditableWorkflowProfileUpdatedEvent",
    "AuditableWorkflowRejectedEvent",
    "AuditableWorkflowRequestMadeEvent",
    "AuditableWorkflowRestApiEvent",
    "AuditableWorkflowReviewedEvent",
    "AuditableWorkflowRunningWorkflowEvent",
    "AuditableWorkflowSoapApiEvent",
    "AuditableWorkflowStatusChangedEvent",
    "AuditableWorkflowStoredProcedureEvent",
    "AuditableWorkflowUnassignEvent",
    "AuditableWorkflowWaitingForWorkflowEvent",
    "AuditableWorkflowWorkflowChangedEvent",
    "ActiveRecordCreate",
    "ActiveRecordUpdate",
    "ActiveRecordDestroy",
    "AuditableApiEvent",
)

AUDIT_API_METHOD_EVENT_TYPES = ("Get", "Post", "Patch", "Delete")

ADVANCED_SEARCH_SQL_STYLE_KEYS = {"field", "operator", "condition"}
ADVANCED_SEARCH_REQUIRED_KEYS = ("condition_rules_attributes",)

# Constrained value sets used across tool params/schemas.
WORKFLOW_SESSION_STATUSES = (
    "waiting on workflow",
    "identity proofing completed",
    "new",
    "closing",
    "pending request",
    "requested",
    "pending approval",
    "approved",
    "pending notification",
    "notified",
    "pending review",
    "reviewed",
    "pending trigger",
    "stored procedure",
    "pending status change",
    "status changed",
    "pending update",
    "non employee updated",
    "non employee created",
    "pending creation",
    "rejected",
    "pending assignment",
    "assigned",
    "default",
    "failed",
    "un assigned",
    "auto assigned",
    "ldap provided",
    "pending ldap",
    "pending fulfillment",
    "pending stored procedure",
    "pending courion add",
    "fulfilled",
    "pending courion update",
    "courion add",
    "pending courion_extend",
    "courion update",
    "pending courion terminate",
    "courion extend",
    "pending profile select",
    "courion terminate",
    "batch completed",
    "profiles selected",
    "answered questions",
    "pending questions",
    "attempting to start workflow",
    "started workflow",
    "profile check complete",
    "completed",
    "processing",
    "pending set attribute",
    "invitation sent",
    "action skipped",
    "api request sent",
    "attribute set",
    "disabled",
    "duplicates resolved",
    "soap request sent",
    "checking for duplicates",
    "pending identity proofing",
    "closed",
    "workflow changed",
)

PROFILE_STATUSES = ("Active", "Inactive", "On Leave", "Terminated")
USER_STATUSES = ("Active", "Pending", "Disabled")
USER_TYPES = ("NeprofileUser", "NeaccessUser")
ROLE_TYPES = ("NeprofileRole", "NeaccessRole", "IdproxyRole")
RELATIONSHIP_TYPES = ("owner", "contributor")
IDENTITY_PROOFING_RESULTS = ("pass", "fail")
ATTRIBUTE_DATA_TYPES = (
    "text field",
    "text area",
    "drop-down",
    "radio buttons",
    "check boxes",
    "date",
    "tags",
    "attachment",
    "profile select",
    "profile search",
    "owner select",
    "owner search",
    "contributor select",
    "contributor search",
)
ISC_ACCOUNT_CATEGORIES = ("non-employee", "assignment")
ISC_ACCOUNT_STATUSES = ("active", "inactive", "on leave", "terminated")
PROFILE_TYPE_SYNCED_FILTERS = ("synced", "unsynced", "all")
RISK_SCORE_OBJECT_TYPES = ("Profile", "WorkflowSession")
